/*
Streaming Availability API

Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 59 countries!

API version: 3.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package streaming

import (
	"encoding/json"
)

// checks if the UpcomingChangesResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpcomingChangesResponseSchema{}

// UpcomingChangesResponseSchema struct for UpcomingChangesResponseSchema
type UpcomingChangesResponseSchema struct {
	// Array of the results matched with the query.
	Result []UpcomingChangeSet `json:"result"`
	// Whether there are more results to be loaded.
	HasMore bool `json:"hasMore"`
	// Cursor value to pass to get next set of the results. An empty string if \"hasMore\" is \"false\".
	NextCursor string `json:"nextCursor"`
}

// NewUpcomingChangesResponseSchema instantiates a new UpcomingChangesResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpcomingChangesResponseSchema(result []UpcomingChangeSet, hasMore bool, nextCursor string) *UpcomingChangesResponseSchema {
	this := UpcomingChangesResponseSchema{}
	this.Result = result
	this.HasMore = hasMore
	this.NextCursor = nextCursor
	return &this
}

// NewUpcomingChangesResponseSchemaWithDefaults instantiates a new UpcomingChangesResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpcomingChangesResponseSchemaWithDefaults() *UpcomingChangesResponseSchema {
	this := UpcomingChangesResponseSchema{}
	return &this
}

// GetResult returns the Result field value
func (o *UpcomingChangesResponseSchema) GetResult() []UpcomingChangeSet {
	if o == nil {
		var ret []UpcomingChangeSet
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *UpcomingChangesResponseSchema) GetResultOk() ([]UpcomingChangeSet, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *UpcomingChangesResponseSchema) SetResult(v []UpcomingChangeSet) {
	o.Result = v
}

// GetHasMore returns the HasMore field value
func (o *UpcomingChangesResponseSchema) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *UpcomingChangesResponseSchema) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *UpcomingChangesResponseSchema) SetHasMore(v bool) {
	o.HasMore = v
}

// GetNextCursor returns the NextCursor field value
func (o *UpcomingChangesResponseSchema) GetNextCursor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
func (o *UpcomingChangesResponseSchema) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextCursor, true
}

// SetNextCursor sets field value
func (o *UpcomingChangesResponseSchema) SetNextCursor(v string) {
	o.NextCursor = v
}

func (o UpcomingChangesResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpcomingChangesResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["hasMore"] = o.HasMore
	toSerialize["nextCursor"] = o.NextCursor
	return toSerialize, nil
}

type NullableUpcomingChangesResponseSchema struct {
	value *UpcomingChangesResponseSchema
	isSet bool
}

func (v NullableUpcomingChangesResponseSchema) Get() *UpcomingChangesResponseSchema {
	return v.value
}

func (v *NullableUpcomingChangesResponseSchema) Set(val *UpcomingChangesResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableUpcomingChangesResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableUpcomingChangesResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpcomingChangesResponseSchema(val *UpcomingChangesResponseSchema) *NullableUpcomingChangesResponseSchema {
	return &NullableUpcomingChangesResponseSchema{value: val, isSet: true}
}

func (v NullableUpcomingChangesResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpcomingChangesResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


