/*
Streaming Availability API

Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!

API version: 4.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package streaming

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Service type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Service{}

// Service Details of a streaming service localized according to the parent country.
type Service struct {
	// Id of the service.
	Id string `json:"id"`
	// Name of the service.
	Name string `json:"name"`
	// Link to the homepage of the service.
	HomePage string `json:"homePage"`
	// Associated theme color hex code of the service.
	ThemeColorCode string `json:"themeColorCode"`
	// Image set of the service.
	ImageSet ServiceImageSet `json:"imageSet"`
	StreamingOptionTypes StreamingOptionTypes `json:"streamingOptionTypes"`
	// Array of the supported addons in the service.
	Addons []Addon `json:"addons"`
}

type _Service Service

// NewService instantiates a new Service object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewService(id string, name string, homePage string, themeColorCode string, imageSet ServiceImageSet, streamingOptionTypes StreamingOptionTypes, addons []Addon) *Service {
	this := Service{}
	this.Id = id
	this.Name = name
	this.HomePage = homePage
	this.ThemeColorCode = themeColorCode
	this.ImageSet = imageSet
	this.StreamingOptionTypes = streamingOptionTypes
	this.Addons = addons
	return &this
}

// NewServiceWithDefaults instantiates a new Service object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceWithDefaults() *Service {
	this := Service{}
	return &this
}

// GetId returns the Id field value
func (o *Service) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Service) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Service) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Service) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Service) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Service) SetName(v string) {
	o.Name = v
}

// GetHomePage returns the HomePage field value
func (o *Service) GetHomePage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HomePage
}

// GetHomePageOk returns a tuple with the HomePage field value
// and a boolean to check if the value has been set.
func (o *Service) GetHomePageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HomePage, true
}

// SetHomePage sets field value
func (o *Service) SetHomePage(v string) {
	o.HomePage = v
}

// GetThemeColorCode returns the ThemeColorCode field value
func (o *Service) GetThemeColorCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThemeColorCode
}

// GetThemeColorCodeOk returns a tuple with the ThemeColorCode field value
// and a boolean to check if the value has been set.
func (o *Service) GetThemeColorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThemeColorCode, true
}

// SetThemeColorCode sets field value
func (o *Service) SetThemeColorCode(v string) {
	o.ThemeColorCode = v
}

// GetImageSet returns the ImageSet field value
func (o *Service) GetImageSet() ServiceImageSet {
	if o == nil {
		var ret ServiceImageSet
		return ret
	}

	return o.ImageSet
}

// GetImageSetOk returns a tuple with the ImageSet field value
// and a boolean to check if the value has been set.
func (o *Service) GetImageSetOk() (*ServiceImageSet, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageSet, true
}

// SetImageSet sets field value
func (o *Service) SetImageSet(v ServiceImageSet) {
	o.ImageSet = v
}

// GetStreamingOptionTypes returns the StreamingOptionTypes field value
func (o *Service) GetStreamingOptionTypes() StreamingOptionTypes {
	if o == nil {
		var ret StreamingOptionTypes
		return ret
	}

	return o.StreamingOptionTypes
}

// GetStreamingOptionTypesOk returns a tuple with the StreamingOptionTypes field value
// and a boolean to check if the value has been set.
func (o *Service) GetStreamingOptionTypesOk() (*StreamingOptionTypes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StreamingOptionTypes, true
}

// SetStreamingOptionTypes sets field value
func (o *Service) SetStreamingOptionTypes(v StreamingOptionTypes) {
	o.StreamingOptionTypes = v
}

// GetAddons returns the Addons field value
func (o *Service) GetAddons() []Addon {
	if o == nil {
		var ret []Addon
		return ret
	}

	return o.Addons
}

// GetAddonsOk returns a tuple with the Addons field value
// and a boolean to check if the value has been set.
func (o *Service) GetAddonsOk() ([]Addon, bool) {
	if o == nil {
		return nil, false
	}
	return o.Addons, true
}

// SetAddons sets field value
func (o *Service) SetAddons(v []Addon) {
	o.Addons = v
}

func (o Service) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Service) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["homePage"] = o.HomePage
	toSerialize["themeColorCode"] = o.ThemeColorCode
	toSerialize["imageSet"] = o.ImageSet
	toSerialize["streamingOptionTypes"] = o.StreamingOptionTypes
	toSerialize["addons"] = o.Addons
	return toSerialize, nil
}

func (o *Service) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"homePage",
		"themeColorCode",
		"imageSet",
		"streamingOptionTypes",
		"addons",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varService := _Service{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varService)

	if err != nil {
		return err
	}

	*o = Service(varService)

	return err
}

type NullableService struct {
	value *Service
	isSet bool
}

func (v NullableService) Get() *Service {
	return v.value
}

func (v *NullableService) Set(val *Service) {
	v.value = val
	v.isSet = true
}

func (v NullableService) IsSet() bool {
	return v.isSet
}

func (v *NullableService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableService(val *Service) *NullableService {
	return &NullableService{value: val, isSet: true}
}

func (v NullableService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


