/*
Streaming Availability API

Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 58 countries!

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package streaming

import (
	"encoding/json"
)

// checks if the GetResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetResponseSchema{}

// GetResponseSchema struct for GetResponseSchema
type GetResponseSchema struct {
	Result Show `json:"result"`
}

// NewGetResponseSchema instantiates a new GetResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetResponseSchema(result Show) *GetResponseSchema {
	this := GetResponseSchema{}
	this.Result = result
	return &this
}

// NewGetResponseSchemaWithDefaults instantiates a new GetResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetResponseSchemaWithDefaults() *GetResponseSchema {
	this := GetResponseSchema{}
	return &this
}

// GetResult returns the Result field value
func (o *GetResponseSchema) GetResult() Show {
	if o == nil {
		var ret Show
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *GetResponseSchema) GetResultOk() (*Show, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *GetResponseSchema) SetResult(v Show) {
	o.Result = v
}

func (o GetResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableGetResponseSchema struct {
	value *GetResponseSchema
	isSet bool
}

func (v NullableGetResponseSchema) Get() *GetResponseSchema {
	return v.value
}

func (v *NullableGetResponseSchema) Set(val *GetResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGetResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGetResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetResponseSchema(val *GetResponseSchema) *NullableGetResponseSchema {
	return &NullableGetResponseSchema{value: val, isSet: true}
}

func (v NullableGetResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


