/*
Streaming Availability API

Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!

API version: 4.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package streaming

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServiceInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceInfo{}

// ServiceInfo Details of the streaming service localized according to the parent country.
type ServiceInfo struct {
	// Id of the service.
	Id string `json:"id"`
	// Name of the service.
	Name string `json:"name"`
	// Link to the homepage of the service.
	HomePage string `json:"homePage"`
	// Associated theme color hex code of the service.
	ThemeColorCode string `json:"themeColorCode"`
	// Image set of the service.
	ImageSet ServiceImageSet `json:"imageSet"`
}

type _ServiceInfo ServiceInfo

// NewServiceInfo instantiates a new ServiceInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceInfo(id string, name string, homePage string, themeColorCode string, imageSet ServiceImageSet) *ServiceInfo {
	this := ServiceInfo{}
	this.Id = id
	this.Name = name
	this.HomePage = homePage
	this.ThemeColorCode = themeColorCode
	this.ImageSet = imageSet
	return &this
}

// NewServiceInfoWithDefaults instantiates a new ServiceInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceInfoWithDefaults() *ServiceInfo {
	this := ServiceInfo{}
	return &this
}

// GetId returns the Id field value
func (o *ServiceInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ServiceInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ServiceInfo) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ServiceInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceInfo) SetName(v string) {
	o.Name = v
}

// GetHomePage returns the HomePage field value
func (o *ServiceInfo) GetHomePage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HomePage
}

// GetHomePageOk returns a tuple with the HomePage field value
// and a boolean to check if the value has been set.
func (o *ServiceInfo) GetHomePageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HomePage, true
}

// SetHomePage sets field value
func (o *ServiceInfo) SetHomePage(v string) {
	o.HomePage = v
}

// GetThemeColorCode returns the ThemeColorCode field value
func (o *ServiceInfo) GetThemeColorCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThemeColorCode
}

// GetThemeColorCodeOk returns a tuple with the ThemeColorCode field value
// and a boolean to check if the value has been set.
func (o *ServiceInfo) GetThemeColorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThemeColorCode, true
}

// SetThemeColorCode sets field value
func (o *ServiceInfo) SetThemeColorCode(v string) {
	o.ThemeColorCode = v
}

// GetImageSet returns the ImageSet field value
func (o *ServiceInfo) GetImageSet() ServiceImageSet {
	if o == nil {
		var ret ServiceImageSet
		return ret
	}

	return o.ImageSet
}

// GetImageSetOk returns a tuple with the ImageSet field value
// and a boolean to check if the value has been set.
func (o *ServiceInfo) GetImageSetOk() (*ServiceImageSet, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageSet, true
}

// SetImageSet sets field value
func (o *ServiceInfo) SetImageSet(v ServiceImageSet) {
	o.ImageSet = v
}

func (o ServiceInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["homePage"] = o.HomePage
	toSerialize["themeColorCode"] = o.ThemeColorCode
	toSerialize["imageSet"] = o.ImageSet
	return toSerialize, nil
}

func (o *ServiceInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"homePage",
		"themeColorCode",
		"imageSet",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServiceInfo := _ServiceInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServiceInfo)

	if err != nil {
		return err
	}

	*o = ServiceInfo(varServiceInfo)

	return err
}

type NullableServiceInfo struct {
	value *ServiceInfo
	isSet bool
}

func (v NullableServiceInfo) Get() *ServiceInfo {
	return v.value
}

func (v *NullableServiceInfo) Set(val *ServiceInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceInfo(val *ServiceInfo) *NullableServiceInfo {
	return &NullableServiceInfo{value: val, isSet: true}
}

func (v NullableServiceInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


