/*
Streaming Availability API

Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 59 countries!

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package streaming

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerticalImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerticalImage{}

// VerticalImage Horizontal image of a show.
type VerticalImage struct {
	// Link to the 240px wide version of the image.
	W240 string `json:"w240"`
	// Link to the 360px wide version of the image.
	W360 string `json:"w360"`
	// Link to the 480px wide version of the image.
	W480 string `json:"w480"`
	// Link to the 600px wide version of the image.
	W600 string `json:"w600"`
	// Link to the 720px wide version of the image.
	W720 string `json:"w720"`
}

type _VerticalImage VerticalImage

// NewVerticalImage instantiates a new VerticalImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerticalImage(w240 string, w360 string, w480 string, w600 string, w720 string) *VerticalImage {
	this := VerticalImage{}
	this.W240 = w240
	this.W360 = w360
	this.W480 = w480
	this.W600 = w600
	this.W720 = w720
	return &this
}

// NewVerticalImageWithDefaults instantiates a new VerticalImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerticalImageWithDefaults() *VerticalImage {
	this := VerticalImage{}
	return &this
}

// GetW240 returns the W240 field value
func (o *VerticalImage) GetW240() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.W240
}

// GetW240Ok returns a tuple with the W240 field value
// and a boolean to check if the value has been set.
func (o *VerticalImage) GetW240Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.W240, true
}

// SetW240 sets field value
func (o *VerticalImage) SetW240(v string) {
	o.W240 = v
}

// GetW360 returns the W360 field value
func (o *VerticalImage) GetW360() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.W360
}

// GetW360Ok returns a tuple with the W360 field value
// and a boolean to check if the value has been set.
func (o *VerticalImage) GetW360Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.W360, true
}

// SetW360 sets field value
func (o *VerticalImage) SetW360(v string) {
	o.W360 = v
}

// GetW480 returns the W480 field value
func (o *VerticalImage) GetW480() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.W480
}

// GetW480Ok returns a tuple with the W480 field value
// and a boolean to check if the value has been set.
func (o *VerticalImage) GetW480Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.W480, true
}

// SetW480 sets field value
func (o *VerticalImage) SetW480(v string) {
	o.W480 = v
}

// GetW600 returns the W600 field value
func (o *VerticalImage) GetW600() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.W600
}

// GetW600Ok returns a tuple with the W600 field value
// and a boolean to check if the value has been set.
func (o *VerticalImage) GetW600Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.W600, true
}

// SetW600 sets field value
func (o *VerticalImage) SetW600(v string) {
	o.W600 = v
}

// GetW720 returns the W720 field value
func (o *VerticalImage) GetW720() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.W720
}

// GetW720Ok returns a tuple with the W720 field value
// and a boolean to check if the value has been set.
func (o *VerticalImage) GetW720Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.W720, true
}

// SetW720 sets field value
func (o *VerticalImage) SetW720(v string) {
	o.W720 = v
}

func (o VerticalImage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerticalImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["w240"] = o.W240
	toSerialize["w360"] = o.W360
	toSerialize["w480"] = o.W480
	toSerialize["w600"] = o.W600
	toSerialize["w720"] = o.W720
	return toSerialize, nil
}

func (o *VerticalImage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"w240",
		"w360",
		"w480",
		"w600",
		"w720",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerticalImage := _VerticalImage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerticalImage)

	if err != nil {
		return err
	}

	*o = VerticalImage(varVerticalImage)

	return err
}

type NullableVerticalImage struct {
	value *VerticalImage
	isSet bool
}

func (v NullableVerticalImage) Get() *VerticalImage {
	return v.value
}

func (v *NullableVerticalImage) Set(val *VerticalImage) {
	v.value = val
	v.isSet = true
}

func (v NullableVerticalImage) IsSet() bool {
	return v.isSet
}

func (v *NullableVerticalImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerticalImage(val *VerticalImage) *NullableVerticalImage {
	return &NullableVerticalImage{value: val, isSet: true}
}

func (v NullableVerticalImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerticalImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


